### ISSUE TITLE
Add ability to email someone directly

### ISSUE THREAD

**Issue by bradmac** [anhnt/videosurvey#7]
When i create a survey, I will want to sent it to someone, and possibly that will be a new user.

So please add the ability to
- send an email with a link to the survey from the manage survey page
- this may be a new user account, so create the profile if it doesnt exist (matching on email address)

**Comment by anhnt** [comment]
Hey @bradmac,

I've done this feature: http://admin.anhnt.olhub.com/vidsurvey/survey-105fPGhhLimFiWu11ijqVdVl88vl2O/#sendEmail-tab

One thing: login token seems not work in this case: `.html('@{login}')` for example

**Comment by tuzzmaniandevil** [comment]
.html() of the email builder doesn't support templating. You can use the Content app if you want to eval templates. But you still need to pass it what parameters are available to template.

So to generate a login token there is a function on the WebsiteRootFolder and on the ManageWebsiteBranchFolder called getLoginToken

Since you are doing this from the admin you will need to use ManageWebsiteBranchFolder which you can do by:

```
var mwbf = page.find('/websites/anh/').current;
var loginToken = mwbf.getLoginToken(profile);
```

You need to pass either a Profile, UserResource or ProfileBean to getLoginToken

**Comment by anhnt** [comment]
done
